### PR TITLE
Split test_problems.py into test_*.py for each class

### LINKED ISSUE #226: Improve test_problems.py
### Issue Description
- The file is too long and contains tests for all problem classes. We need to break it down as separate files testing each problem class for ease of maintainability.
- The tests contain some unused code and non consistent coding standards that need to be fixed.

### PR DESCRIPTION
**Pull request by Newtech66**
## Description

- Split `test_problems.py` into several `test_*.py` files which each contain the tests for a particular problem class.
- **Resolves #226**

## Checklist

[//]: <> (- [ ] My code follows the style guidelines of this project)

- [x] I have performed a self-review of my code.
- [x] I have commented my code and used numpy-style docstrings
- [x] I have made corresponding updates to the documentation.
- [ ] My changes generate no new warnings
- [x] I have added/updated tests to make sure bugfix/feature works.
- [ ] New and existing unit tests pass locally with my changes.

[//]: <> (- [ ] Any dependent changes have been merged and published in downstream modules)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

`PortfolioOptimization` has been added to `test_QUBO.py`, but it doesn't pass on my system because the change to `helper_functions.py` isn't reflecting on the install for some reason.

### CODE REVIEW

**Comment by vishal-ph** [comment]
@newton66, can you please update your branch by pulling in the latest changes from `dev`. We realized there was an issue with the `test_ext_dev` action script that prevented the tests inside `src/*/tests/` folders to run. We have fixed this in the latest commit on `dev`. Once you have pulled these changes, we can run the tests again

**Comment by Newtech66** [comment]
@vishal-ph I did it

**Comment by vishal-ph** [comment]
@Newtech66, I cannot see the new changes on your branch yet, could you please merge the branch once more? Thanks

**Comment by vishal-ph** [comment]
The only test that failed in this PR was due to IBM account credentials being inaccessible by forked PRs. The PR is good to merge

**Review by vishal-ph — APPROVED** [review]

**Pull request merged**
