### PR TITLE
Dev optimizers notebook

### PR DESCRIPTION
**Pull request by raulconchello**
New Notebook example. It is about the optimizers.

It has no number yet, before merging we should give it a number and change its name.

### CODE REVIEW

**Comment by Q-lds** [comment]
This is a very nice notebook! :tada: 

It will also make sense to have something similar on the website :)

**Comment by vishal-ph** [comment]
Very nice notebook, @raulconchello. Congratulations! 

Just one comment, in the section for gradient-free optimizers, I can see `newton-cg`, and `l-bfgs-b` algorithms in the list as well. Be careful, since they require a jacobian for optimization, and therefore, are not gradient-free

**Comment by raulconchello** [comment]
@vishal-ph I have changed what you said.

However, before merging I think we should give it a number.

**Comment by Q-lds** [comment]
How about 13? :D 

Also, is the notebook already featured in `/tests/test_notebooks.py` and in the docs?

**Comment by raulconchello** [comment]
@Q-lds
We can give it the 13, but I feel that the notebooks increase in difficulty and this one is not that technical. 
What do you think, @vishal-ph ?

**Comment by vishal-ph** [comment]
fair point, @raulconchello. Even though it was never a conscious plan to rank the notebooks in increasing order of complexity, it is possible that's how it looks at the moment.

**Comment by Q-lds** [comment]
@vishal-ph and @raulconchello, I think the number of the file is not that relevant. What is important is to organize the notebooks in the docs.

As we already have a lot of them, it probably makes more sense to divide them thematically in the docs and keep a simple increasing counter in the folder

**Comment by vishal-ph** [comment]
sure, then 13 is fine for the moment

**Review by vishal-ph — APPROVED** [review]

**Pull request merged**
