### PR TITLE
Update XY_mixer_hamiltonian with Additional mixer_qubit_conndectivity

### PR DESCRIPTION
**Pull request by yoshioka1128**
## Description

This PR adds new mixer_qubit_connectivity to the ```XY_mixer_hamiltonian``` and ```get_mixer_hamiltonian``` function.

## Checklist

[//]: <> (- [ ] My code follows the style guidelines of this project)

- [x] I have performed a self-review of my code.
- [ ] I have commented my code and used numpy-style docstrings
- [ ] I have made corresponding updates to the documentation.
- [x] My changes generate no new warnings
- [x] I have added/updated tests to make sure bugfix/feature works.
- [x] New and existing unit tests pass locally with my changes.

[//]: <> (- [ ] Any dependent changes have been merged and published in downstream modules)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Add the "cyclic" case to the code in ```test_utilities.py```.

### CODE REVIEW

**Review by KilianPoirier — COMMENTED** [review]
Changes look great! Thanks for implementing the cyclic version of the XY mixer hamiltonian.

The only comment I have is to update the test [here](https://github.com/entropicalabs/openqaoa/blob/7f84b119d8762c83e084cd195f9cbec3293455b7/src/openqaoa-core/tests/test_utilities.py#L64).
Basically adding adding an extra `"cyclic"` case to the following code:
```python
for connectivity in connectivities:
  # Define connectivity explicit indexing
  if connectivity == "full":
    terms_indices = list(itertools.combinations(range(n_qubits), 2))
    input_coefficients = 2 * [1 for _ in range(len(terms_indices))]
    mixer_type = "xy"
  
  elif connectivity == "chain":
    terms_indices = [(i, i + 1) for i in range(n_qubits - 1)]
    input_coefficients = 2 * [1 for _ in range(len(terms_indices))]
    mixer_type = "xy"
  
  elif connectivity == "star":
    terms_indices = [(0, i) for i in range(1, n_qubits)]
    input_coefficients = 2 * [1 for _ in range(len(terms_indices))]
    mixer_type = "xy"

  else:
    input_coefficients = [1 for _ in range(n_qubits)]
    mixer_type = "x"
```

Let me know what you think of this!

**Comment by yoshioka1128** [comment]
Thank you for your feedback! I think adding the cyclic case to the test is a great idea. I will proceed with the following updates to the test code:

1. Add the "cyclic" case to the connectivities list.
2. Implement the necessary logic for the cyclic connectivity in the loop.

I'll make these changes and update the PR shortly. Please let me know if you have any additional suggestions or concerns.

**Comment by yoshioka1128** [comment]
Thank you for your feedback! I have added the cyclic connectivity test cases as requested.

Here are the test results:

```
........................
Qubits in the specified Hamiltonian are remapped to [0]. Please specify the physical quantum register as a qubit layout argument in the backend.
Qubits in the specified Hamiltonian are remapped to [0, 1, 2]. Please specify the physical quantum register as a qubit layout argument in the backend.
...
----------------------------------------------------------------------
Ran 27 tests in 0.294s

OK
```
All tests passed successfully.
The warnings about qubit remapping are not errors and do not affect the test results.
Please let me know if there are any further changes or additional tests needed.

**Review by KilianPoirier — APPROVED** [review]
The code looks great!
Thank you for implementing the cyclic version of the XY-mixer Hamiltonian

**Pull request merged**
