### PR TITLE
Bug fix for isolated nodes when running RQAOA

### PR DESCRIPTION
**Pull request by kidiki**
## Description
Bug fix for isolated nodes when running RQAOA
- **Fixes # (issue)**
For solving the MaxCut problem on unweighted graphs the isolated nodes were not captured and fixed arbitrarily for some particular instances. As a result, the elimination schedule was missing one of the eliminations and throwing an error "list out of range" when reconstructing the solution. 

The current solution is to keep track of the number of eliminations which have to take place at each step reconstructing them from the spin map. Then, comparing the new register either to the quadratic one, a s before, or to the old one - number of eliminations.

## Checklist

[//]: <> (- [ ] My code follows the style guidelines of this project)

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code and used numpy-style docstrings
- [ ] I have made corresponding updates to the documentation.
- [ ] My changes generate no new warnings
- [ ] I have added/updated tests to make sure bugfix/feature works.
- [ ] New and existing unit tests pass locally with my changes.

[//]: <> (- [ ] Any dependent changes have been merged and published in downstream modules)

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Name the new unit-tests that you have added along with this change.

### CODE REVIEW

**Comment by kidiki** [comment]
The failed tests are assertion errors for the angles with precision 10^-16. Is this really necessary?

**Comment by Q-lds** [comment]
Why all those tests? Did you issue a PR to `main` and then change it to `dev`

**Comment by Q-lds** [comment]
Also, it is very interesting that the tests are all green for Linux but consistently fail for all mac/windows. It must be something to do with different ways of rounding numbers across different OS

**Comment by Q-lds** [comment]
and @kidiki it looks like the errors are a bit larger:

```
FAILED tests/test_results.py::TestingRQAOAResultOutputs::test_rqaoa_result_methods_steps - AssertionError: Optimized angles are not correct
assert [0.3386847452...0316893752504] == [0.3404859432...5304635645852]
  At index 0 diff: 0.3386847452289164 != 0.34048594327263326
```

see https://github.com/entropicalabs/openqaoa/actions/runs/3764081183/jobs/6398159774#step:6:363

**Review by vishal-ph — APPROVED** [review]

**Pull request merged**
