### PR TITLE
QAOA benchmark

### PR DESCRIPTION
**Pull request by raulconchello**
Benchmark object for qaoa

- [x] Qaoa Benchmark object
- [x] decide the import
- [x] Create reference object
- [x] Run method for benchmarked object and reference
- [x] When running the benchmark it evaluates the points such that at each round there is more resolution
- [x] Plot method for results
- [x] Difference property between benchmarked values and reference
- [x] Mean difference property
- [x] Notebook
- [x] Tests

For examples read notebook 14 (new), here is a simple example:
```
from openqaoa import QAOA, create_device, QAOABenchmark
from openqaoa.problems import QUBO

qaoa = QAOA()
qaoa.set_device(create_device(name='qiskit.shot_simulator', location='local'))
qaoa.compile(QUBO.random_instance(5))
benchmark = QAOABenchmark(qaoa)
benchmark.run(n_points_axis=2**4, ranges=[(0,1),(0,1)], plot=True)
```

### CODE REVIEW

**Comment by raulconchello** [comment]
@shahidee44, @vishal-ph Which import do you think is appropriate for this object?

now is: `from openqaoa.algorithms.qaoa import QAOABenchmark`

**Comment by Q-lds** [comment]
> now is: `from openqaoa.algorithms.qaoa import QAOABenchmark`

I think it can easily be 
`from openqaoa import QAOABenchmark`

**Comment by vishal-ph** [comment]
@raulconchello, sorry if I missed the discussion, but why is this PR going into `dev_evaluate_circuit`?

**Comment by vishal-ph** [comment]
NOTE: run `black` formatter before merging

**Review by vishal-ph — APPROVED** [review]

**Pull request merged**
